## Week 4 - Systems of Linear Equations

In [2]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import inv

## Demo code

Find the inverse of a matrix.

In [12]:
A = np.array([
    [1,2],
    [3,4]
])

det_A = det(A)
A_inv = np.linalg.inv(A)
A_T = np.transpose(A)

adj_A = det_A * A_inv

print("A =\n", A)
print("A_T = \n", A_T)
print("det(A) = \n", det_A)
print("adj(A) =\n", adj_A)
print("inv(A)=\n", A_inv)

A =
 [[1 2]
 [3 4]]
A_T = 
 [[1 3]
 [2 4]]
det(A) = 
 -2.0000000000000004
adj(A) =
 [[ 4. -2.]
 [-3.  1.]]
inv(A)=
 [[-2.   1. ]
 [ 1.5 -0.5]]


# Question 1

In [4]:
x = np.array([
    [1,1],
    [3,4]
])
y = np.array([
    [0],
    [1]
])

print(np.linalg.inv(x) @ y)

[[-1.]
 [ 1.]]


# Question 2


In [6]:
x = np.array([
    [1,2],
    [3,6]
])

y = np.array([
    [0],
    [1]
])

print(np.linalg.det(x))

0.0


# Question 3

In [9]:
X = np.array([
    [1,2],
    [2,4],
    [1,-1]
])

Y = np.array([
    [0],
    [0.1],
    [1]
])

print(np.linalg.det(X.T @ X))

print(np.linalg.inv(X.T @ X) @ X.T @ Y)

44.99999999999999
[[ 0.68]
 [-0.32]]


# Question 4

In [17]:
X = np.array([
    [1,0,1,0],
    [1,-1,1,-1],
    [1,1,0,0]
])
Y = np.array([
    [1],
    [0],
    [1]
])

print(np.linalg.matrix_rank((X @ X.T)))
print(np.linalg.det (X @ X.T))
print(np.linalg.inv(X.T @ X) @ X.T @ Y)

3
4.0
[[1. ]
 [0.5]
 [0. ]
 [0.5]]


# Question 5

In [21]:
X = np.array([
    [1,2],
    [3,6]
])

print(np.linalg.inv(X)) #X is a singular matrix

LinAlgError: Singular matrix

# Question 6

In [23]:
X = np.array([
    [1,2],
    [2,4],
    [1,-1]
])

Y = np.array([
    [0],
    [1]
]
)

X_T = np.transpose(X)

w = X_T.T @ np.linalg.inv(X_T @ X_T.T) @ Y
print(w)

[[ 0.06666667]
 [ 0.13333333]
 [-0.33333333]]


# Question 7


In [27]:
X = np.array([
    [2,0,0],
    [0,0,1]
])

print(np.linalg.det(X @ X.T))
# Since det(XX^T) != 0, right inverse exist
print(np.linalg.det(X.T @ X))
# Since det(X^TX) != 0, left inverse does not exist


4.0
0.0


# Question 8

In [28]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

A_T = np.transpose(A)

print(det(A_T@A)) #left invertible
print(det(A@A_T)) #right invertible
print(det(A)) #det for square matrix does not exist

0.0
54.00000000000001


LinAlgError: Last 2 dimensions of the array must be square